"""empty message

Revision ID: 46646acdcccb
Revises: 
Create Date: 2020-03-27 10:35:38.065550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46646acdcccb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('product', sa.String(length=20), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=50), nullable=False),
    sa.Column('paras', sa.Text(), nullable=False),
    sa.Column('osign_list', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('api')
    # ### end Alembic commands ###
